export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function AuthLayout({ children }: { children: React.ReactNode | string }) {
    return <div className="h-full grid place-content-center">{children}</div>;
}
